Repository LamArt/open-schools-platform, pull requests merged in 2022-11, with the labels that each got.

#114 Feature/add student to circle
  open_schools_platform/organization_management/circles/serializers.py
  open_schools_platform/organization_management/circles/services.py
  open_schools_platform/organization_management/circles/urls.py
  open_schools_platform/organization_management/circles/views.py
  open_schools_platform/organization_management/employees/services.py
  open_schools_platform/parent_management/parents/services.py
  open_schools_platform/query_management/queries/migrations/0004_auto_20221105_1715.py
  open_schools_platform/student_management/students/filters.py
  open_schools_platform/student_management/students/migrations/0005_alter_studentprofile_age.py
  open_schools_platform/student_management/students/models.py
  open_schools_platform/student_management/students/services.py
  open_schools_platform/tasks/tasks.py
  templates/new_user_circle_invite_mail_form.html
Labels: enhancement, question

#121 Feature/school 442/adding export
  config/django/base.py
  open_schools_platform/api/mixins.py
  open_schools_platform/organization_management/circles/tests/utils.py
  open_schools_platform/organization_management/circles/tests/views/test_circle_exceptions.py
  open_schools_platform/organization_management/circles/tests/views/test_circle_students_export_api.py
  open_schools_platform/organization_management/circles/urls.py
  open_schools_platform/organization_management/circles/views.py
  open_schools_platform/organization_management/organizations/tests/views/test_organization_students_export_api.py
  open_schools_platform/organization_management/organizations/tests/views/test_organizations_exceptions.py
  open_schools_platform/organization_management/organizations/urls.py
  open_schools_platform/organization_management/organizations/views.py
  open_schools_platform/photo_management/photos/tests/views/test_photo_update_exceptions.py
  open_schools_platform/student_management/students/exports.py
  open_schools_platform/student_management/students/selectors.py
  open_schools_platform/student_management/students/services.py
  open_schools_platform/student_management/students/tests/services/test_student_services.py
  requirements/base.txt
  setup.cfg
Labels: enhancement, good first issue, invalid

#122 add get request for student
  open_schools_platform/common/serializers.py
  open_schools_platform/organization_management/organizations/urls.py
  open_schools_platform/organization_management/organizations/views.py
  open_schools_platform/parent_management/parents/filters.py
  open_schools_platform/student_management/students/serializers.py
Labels: enhancement, invalid

#123 Feature/school 445/organization logging
  config/django/base.py
  open_schools_platform/api/swagger_tags.py
  open_schools_platform/api/urls.py
  open_schools_platform/common/models.py
  open_schools_platform/history_management/__init__.py
  open_schools_platform/history_management/apps.py
  open_schools_platform/history_management/serializers/__init__.py
  open_schools_platform/history_management/serializers/circle_serializer.py
  open_schools_platform/history_management/serializers/employee_serializer.py
  open_schools_platform/history_management/serializers/fields.py
  open_schools_platform/history_management/serializers/organization_serializer.py
  open_schools_platform/history_management/serializers/student_serializer.py
  open_schools_platform/history_management/serializers/user_serializer.py
  open_schools_platform/history_management/urls.py
  open_schools_platform/history_management/views.py
  open_schools_platform/organization_management/circles/migrations/0006_added_history_records.py
  open_schools_platform/organization_management/employees/migrations/0012_added_history_records.py
  open_schools_platform/organization_management/organizations/migrations/0004_added_history_records.py
  open_schools_platform/parent_management/families/migrations/0004_added_history_records.py
  open_schools_platform/parent_management/parents/migrations/0003_added_history_records.py
  open_schools_platform/photo_management/photos/migrations/0003_added_history_records.py
  open_schools_platform/query_management/queries/migrations/0007_added_history_records.py
  open_schools_platform/student_management/students/migrations/0007_added_history_records.py
  open_schools_platform/student_management/students/models.py
  open_schools_platform/user_management/users/migrations/0006_added_history_records_with_fixes.py
  open_schools_platform/user_management/users/models.py
  open_schools_platform/user_management/users/serializers.py
Labels: enhancement

#108 updated readme
  docs/deploy.md
Labels: documentation
